// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpcakTowYbSWzN823iVNWRyxGrVj4PGho',
    appId: '1:54875392329:android:2c87bef1aea390bccaf298',
    messagingSenderId: '54875392329',
    projectId: 'mypfe-3f4dc',
    databaseURL: 'https://mypfe-3f4dc-default-rtdb.firebaseio.com',
    storageBucket: 'mypfe-3f4dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5tZOZraWRbmnWHC_IyOuXB9aeBDJdPuY',
    appId: '1:54875392329:ios:3951a269a782a084caf298',
    messagingSenderId: '54875392329',
    projectId: 'mypfe-3f4dc',
    databaseURL: 'https://mypfe-3f4dc-default-rtdb.firebaseio.com',
    storageBucket: 'mypfe-3f4dc.firebasestorage.app',
    iosBundleId: 'com.example.myPfe',
  );
}
